project_id = "hhsvraqchtqqgaezhnzn"

[functions.admin-create-user]
verify_jwt = true

[functions.aqua-assistant]
verify_jwt = true

[functions.aquapilote-recommendation]
verify_jwt = true

[functions.create-team-member-account]
verify_jwt = true

[functions.reset-team-member-password]
verify_jwt = true

[functions.send-stock-alert]
verify_jwt = true

[functions.feeding-reminders]
verify_jwt = false
