// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://icroityeownvetvaorzd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imljcm9pdHllb3dudmV0dmFvcnpkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjAyNTU3NjEsImV4cCI6MjA3NTgzMTc2MX0.9PSLQS_m5Ms1-TelIwwqAV8saTIxcLo6lOMXjH6xPWc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});